apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/rbd
parameters:
    monitors: 10.10.10.23:6789,10.10.10.24:6789,10.10.10.25:6789
    adminId: kube
    adminSecretName: ceph-secret
    adminSecretNamespace: kube-system
    pool: kube
    userId: kube
    userSecretName: ceph-secret-user
