apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      serviceAccountName: ingress
      volumes:
      #- name: ssl
       # secret:
        #  secretName: traefik-cert
      #- name: config
       # configMap:
        #  name: traefik-conf
      - name: log
        hostPath:
          path: /var/log/traefik
          type: Directory
      hostNetwork: true
      containers:
      - image: traefik
        name: traefik-ingress
        volumeMounts:
        #- mountPath: "/ssl"
         # name: "ssl"
        #- mountPath: "/config"
         # name: "config"
        - mountPath: "/log"
          name: "log"
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        #- name: https
         # containerPort: 443
          #hostPort: 443
        args:
        - --configfile=/config/traefik.toml
        - --web
        - --kubernetes
        - --logLevel=DEBUG
        - --web.address=:8580
        #- --web.metrics
        #- --web.metrics.prometheus
        #- --web.metrics.prometheus.buckets= "[0.1 0.3 1.2 5]"
        #- --web.metrics.datadog
        #- --web.metrics.datadog.address= "prometheus.monitoring:9090"
