apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  labels:
    name: traefik
spec:
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: https
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
  - protocol: TCP
    name: admin
    port: 8580
    targetPort: http
  selector:
    name: traefik-ingress-lb

