defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/root/Downloads/k8s/k8s/traefik-ingress/ssl/domain.com.crt"
      KeyFile = "/root/Downloads/k8s/k8s/traefik-ingress/ssl/domain.com.key"
