---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.107.1
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker
        ports:
        - name: http
          containerPort: 8080
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
  - name: http
    port: 80
    targetPort: 8080
