apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-web
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.10.10.23:6789,10.10.10.24:6789,10.10.10.25:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: galera
  pool: rbd 
  userId: admin
  userSecretName: ceph-secret
