apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: galera
  labels:
    app: mysql
data:
  # Root password: changeit run  echo -n jimmysong|base64
   root-password: cm9vdA==
       # Root user: root
   root-user: cm9vdA==
  
